Added ProxyConfig to ntc_config_command and the ability to pass a string to ntc_show_command
networktocode/ntc-ansible pull request #203
Opened 2018-04-17 12:50 UTC by sheffner1226

Added ProxyCommand functionality to ntc_config_command to enable its use with Cisco CML VIRL (same as the ProxyCommand capability added to ntc_show_command in a previous release).

Added the ability to pass a string variable into ntc_show_command (in_string) for TextFSM parsing.  This will allow us to use standard Ansible modules to manage the connection to network devices while using ntc_show_command to parse the output without having to use temporary text files (the only currently supported method).

2018-04-18 11:46 UTC, itdependsnetworks commented
Something happened on config command, and it rewrote the entire file, I can't tell what is changed. Can you redo that? 

Can we also change it to raw_output to be consistent with raw_file?

2018-05-19 03:00 UTC, jmcgill298 requested changes

2018-05-19 03:00 UTC, jmcgill298 commented on library/ntc_config_command.py
> +    connection_args:
This should follow the implementation in `ntc_show_command`

2018-05-19 03:00 UTC, jmcgill298 commented on library/ntc_config_command.py
> +            - Path to SSH configuration file for use by netmike, required when using proxy
misspelled netmiko

2018-05-19 03:00 UTC, jmcgill298 commented on library/ntc_config_command.py
> +        module.fail_json(msg="Error executing command:\
It looks like you have a carriage return instead of using a newline

2018-05-19 03:00 UTC, jmcgill298 commented on library/ntc_show_command.py
> +    in_string:
Please open a separate PR per feature change

2018-05-19 03:01 UTC, jmcgill298 commented on library/ntc_show_command.py
> +    in_string = module.params['in_string']
this should be named `raw_string`

2023-04-08 04:08 UTC, jeffkala commented
Should be closed and retested after #268 is merged.

2023-04-10 20:19 UTC, jeffkala commented
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.

2023-04-10 20:19 UTC, closed without merging