ntc_show_command: better to fail on parse errors?
networktocode/ntc-ansible pull request #246
Opened 2019-08-28 15:34 UTC by sumkincpp

Currently, there is no way to track parsing errors in `ntc_show_command` module

Whenever there were a mistake or template was missing, you still get
- response, response_list as arrays
- changed, failed set to always False

Better to track parsing errors explicitly in playbooks or suppress through `ignore_errors: True`.

2019-10-23 13:29 UTC, jmcgill298 commented
All new templates in ntc-templates raise an error if a line was not matched, which will prevent returning an empty list (assuming there is actually output from the device). If the template raises an Error, then it will raise an Exception.

If there isn't a template, then we prefer to return the command results. This keeps from having to define multiple tasks depending on whether or not a TextFSM template exists.

2019-11-17 22:32 UTC, sumkincpp commented
@jmcgill298  
> All new templates in ntc-templates raise an error if a line was not matched, which will prevent returning an empty list (assuming there is actually output from the device). If the template raises an Error, then it will raise an Exception.

I've looked thoroughly - raising exception might be a problem here when a list of commands/output from multiple devices needs to be parsed. Raising Exception really can help avoiding use case where single output should be parsed.

> If there isn't a template, then we prefer to return the command results. This keeps from having to define multiple tasks depending on whether or not a TextFSM template exists.

If template wasn't provided, then, I agree, module should remove command results. But, if parsing is failed it's also possible to return command results from `fail_msg`. I agree that, the fix should take into account this scenario.

The main use case in terms of using the module is reliable parsing, and I believe that in ansible idiomatically it's better to fail on any uncertainties. 

For example,  If I am a new user of this module, from the basic ntc_show_command I expect
- Always return command results, if they can be obtained from device.
- Fail if a parsing template wasn't found (since I've provided it, I am expecting it to be used and be able to parse results)
- Fail if parsing template can't parse some of the lines, e.g. they are not what expecting. Templates are also expected not to omit unknown lines.

2019-11-20 15:23 UTC, jmcgill298 commented
> I've looked thoroughly - raising exception might be a problem here when a list of commands/output from multiple devices needs to be parsed. Raising Exception really can help avoiding use case where single output should be parsed.

I'm not sure what you are saying here; can you please clarify?

> If template wasn't provided, then, I agree, module should return command results. But, if parsing is failed it's also possible to return command results from `fail_msg`. I agree that, the fix should take into account this scenario.

If the template fails to parse correctly, then TextFSM will return the line that caused an Error; I believe this is sufficient to understand how the template needs to be updated

> * Always return command results, if they can be obtained from device.

I am not against implementing this, but I don't see how this PR accomplishes this

> * Fail if a parsing template wasn't found (since I've provided it, I am expecting it to be used and be able to parse results)

This is not actually true; this works by using CliTable and specifying a directory of templates, and an index file that maps metadata (we use `platform` and `command`) to a specific template. This is why we do not want to raise an exception, since we do not have templates for every command, we do not want to raise an exception if a template doesn't exist for the command.

> * Fail if parsing template can't parse some of the lines, e.g. they are not what expecting. Templates are also expected not to omit unknown lines.

We are in agreement here; but only TextFSM can know if a line was matched by a RegEx or not. This is why all new templates in [ntc-templates](https://github.com/networktocode/ntc-templates) require raising an Error for any unmatched lines. This policy has been in place for a year+ now, but there has not been active work to rectify pre-existing templates. PRs are welcome to update the existing templates.

2019-11-20 15:25 UTC, jmcgill298 requested changes
See conversation

2023-04-08 04:08 UTC, jeffkala commented
Should be closed and retested after #268 is merged.

2023-04-10 20:19 UTC, jeffkala commented
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.

2023-04-10 20:20 UTC, jeffkala commented
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.

2023-04-10 20:20 UTC, closed without merging